---
stages:
  - update

variables:
  GIT_STRATEGY: fetch    # quicker than full clone
  GIT_DEPTH: 1           # shallow fetch
  DEBIAN_FRONTEND: noninteractive

update_blacklist:
  stage: update

  before_script:
    - git config user.name "Aggregator"
    - git config user.email "bl-aggregator@synapsecom.gr"
    - git config --add safe.directory "$CI_PROJECT_DIR"
    - git remote set-url origin "https://${GIT_REPO_TOKEN_NAME}:${GIT_REPO_TOKEN_VALUE}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - chmod +x aggregator.sh optimizer.sh collapser.py
  script:
    - ./aggregator.sh
    - |
      if git diff --quiet --exit-code blacklist.lst; then
        echo "No changes"
      else
        git add blacklist.lst
        git commit -m "🤖 [${CI_PIPELINE_ID}]-[${CI_JOB_ID}] Update aggregated blacklist $(date -u +'%Y-%m-%d %H:%M:%S')"
        git push -o ci.skip
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual
