---
stages:
  - update

variables:
  DEBIAN_FRONTEND: noninteractive

update_blacklist:
  stage: update

  before_script:
    - git remote set-url origin "https://${GIT_REPO_TOKEN_NAME}:${GIT_REPO_TOKEN_VALUE}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git checkout -b main || true
    - git config pull.rebase false || true
    - git switch main
    - git pull origin main --allow-unrelated-histories
    - git config user.name "Aggregator"
    - git config user.email "bl-aggregator@synapsecom.gr"
    - git config --add safe.directory "$CI_PROJECT_DIR"
    - chmod +x aggregator.sh optimizer.sh collapser.py
  script:
    - ./aggregator.sh
    - |
      if git diff --quiet --exit-code blacklist.lst; then
        echo "No changes"
      else
        git add blacklist.lst
        git commit -m "🤖 [${CI_PIPELINE_ID}]-[${CI_JOB_ID}] Update aggregated blacklist $(date -u +'%Y-%m-%d %H:%M:%S')"
        git push --set-upstream origin main -o ci.skip
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual
