---
# Needs AGE_PRIVATE_KEY_FILE env variable (path to age identity private key file)
# Needs GIT_API_TOKEN env variable
# Needs SENTRY_DSN env variable

stages:
  - update

update_blacklist:
  stage: update
  script:
    - git config user.name "CI"
    - git config user.email "ci@synapsecom.gr"
    - chmod +x aggregator.sh optimizer.sh collapser.py
    - ./aggregator.sh
    - git add blacklist.lst
    - |
      if git diff --cached --quiet; then
        echo "No changes"
      else
        git commit -m "🤖 [${CI_PIPELINE_ID}]-[${CI_JOB_ID}] Update aggregated blacklist $(date -u +'%Y-%m-%d %H:%M:%S')"
        git push "https://${GIT_REPO_TOKEN_NAME}:${GIT_REPO_TOKEN_VALUE}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:$CI_COMMIT_REF_NAME -o ci.skip
      fi
  only:
    - main
