---
stages:
  - update

variables:
  GIT_STRATEGY: fetch    # quicker than full clone
  GIT_DEPTH: 1           # shallow fetch
  DEBIAN_FRONTEND: noninteractive

update_blacklist:
  stage: update

  before_script:
    - apt update
    - apt install -y grepcidr git curl
    - git config --global user.email "ci@synapsecom.gr"
    - git config --global user.name "CI"
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - chmod +x aggregator.sh optimizer.sh collapser.py
  script:
    - ./aggregator.sh
    - |
      if git diff --quiet --exit-code blacklist.lst; then
        echo "No changes"
      else
        git add blacklist.lst
        git commit -m "🤖 Update aggregated blacklist $(date -u +'%Y-%m-%d %H:%M:%S') [skip ci]"
        git push "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "HEAD:${CI_COMMIT_REF_NAME}"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual
